namespace PicobootConnection;

public enum picoboot_status : uint
{
    PICOBOOT_OK = 0,
    PICOBOOT_UNKNOWN_CMD = 1,
    PICOBOOT_INVALID_CMD_LENGTH = 2,
    PICOBOOT_INVALID_TRANSFER_LENGTH = 3,
    PICOBOOT_INVALID_ADDRESS = 4,
    PICOBOOT_BAD_ALIGNMENT = 5,
    PICOBOOT_INTERLEAVED_WRITE = 6,
    PICOBOOT_REBOOTING = 7,
    PICOBOOT_UNKNOWN_ERROR = 8,
    PICOBOOT_INVALID_STATE = 9,
    PICOBOOT_NOT_PERMITTED = 10,
    PICOBOOT_INVALID_ARG = 11,
    PICOBOOT_BUFFER_TOO_SMALL = 12,
    PICOBOOT_PRECONDITION_NOT_MET = 13,
    PICOBOOT_MODIFIED_DATA = 14,
    PICOBOOT_INVALID_DATA = 15,
    PICOBOOT_NOT_FOUND = 16,
    PICOBOOT_UNSUPPORTED_MODIFICATION = 17,
}
